name: Update Repo

on:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master
      - name: Download world map
        run: |
          wget https://github.com/eried/portapack-mayhem/releases/download/world_map/world_map.zip
          unzip world_map.zip -d ADSB
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          default_author: github_actions
          message: '[ci/cd] Update Resources'
          pathspec_error_handling: exitImmediately
